site_name: NorgeINFO 🇺🇦 🇳🇴
theme:
  font:
    text: Montserrat
  name: material
  custom_dir: overrides
  palette:
      primary: custom
  language: uk
  favicon: assets/favicon.png
  features:
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.share
    - navigation.top
    - content.tooltips
  icon:
    annotation: material/chevron-down-circle
    logo: material/information-box

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Главная: 'index.md'
  - Коллективная защита: 'kollektiv-beskyttelse.md'
  - Інтродукційна (ознайомча) програма: 'introduksjonsprogram.md'
  - Домашні тварини з України: 'kjaeledyr.md'
  - Водителям: 'forerkort-og-bil.md'
  - Пособия и выплаты: 'stotte.md'
  - Жилье и временное размещение: 'bolig.md'
  - Статистика: 'statistikk.md'
  - Освіта в Норвегії: 'utdanning.md'
  - Робота в Норвегії: 'jobb.md'
  - Медична допомога: 'helsehjelp.md'
  - Разрешение на постоянное пребывание: 'permanent-oppholdstillatelse.md'


plugins:
  - glightbox
  - redirects:
      redirect_maps:
        'collective-protection.md': 'kollektiv-beskyttelse.md'
        'introduction-programme.md': 'introduksjonsprogram.md'
        'animals.md': 'kjaeledyr.md'
        'other.md': 'index.md'
        'work.md': 'jobb.md'
        'stats.md': 'statistikk.md'
        'housing.md': 'bolig.md'
        'automobile.md': 'forerkort-og-bil.md'
        'permanent-residency.md': 'permanent-oppholdstillatelse.md'
        'benefits.md': 'stotte.md'
        'annet.md': 'index.md'
  - search:
      lang: 
        - ru
        - en
  - git-revision-date-localized:
      locale: uk  

markdown_extensions:
- footnotes
- abbr
- attr_list
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- footnotes
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
      alternate_style: true
- pymdownx.snippets:
      auto_append:
        - includes/links.md
copyright: Слава Україні!